name       : liferea
version    : 1.14.5
release    : 29
source     :
    - https://github.com/lwindolf/liferea/archive/refs/tags/v1.14.5.tar.gz : aad3aebcdbbd92d4827f2c94bc62411f93808e2cd109af07e27574fe9cbc739c
license    : GPL-2.0-only
homepage   : https://lzone.de/liferea
component  : network.news
summary    : A desktop feed reader and news aggregator
description: |
    A desktop feed reader and news aggregator
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libxslt)
    - pkgconfig(webkit2gtk-4.0)
    - gettext-devel
rundeps    :
    - python3-cairo # tray icon plugin
environment: |
    export WEBKIT_DISABLE_COMPOSITING_MODE=1 # temp workaround: https://github.com/lwindolf/liferea/issues/767
setup      : |
    %autogen --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
