name       : liferea
version    : '1.12.03'
release    : 5
source     :
    - https://github.com/lwindolf/liferea/releases/download/v1.12-rc3/liferea-1.12-rc3.tar.bz2 : 798e2d54c7b212e3763bcb08048bc261a9443a26c3d3d49bd197b08d7584a635
license    : GPL-2.0
component  : network.news
summary    : A desktop feed reader and news aggregator
description: |
    A desktop feed reader and news aggregator
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
