name       : liferea
version    : 1.10.19
release    : 1
source     :
    - https://github.com/lwindolf/liferea/archive/v1.10.19.tar.gz : a322ad17d3fa0a84f388ee02ddf8e7602d41706256dc0a65d24b27b182b0eeb5
license    : GPL-2.0
component  : network.util
summary    : A desktop feed reader and news aggregator
description: |
    A desktop feed reader and news aggregator
builddeps  :
    - pkgconfig(libnotify)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gthread-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(pango)
setup      : |
    %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
