name       : liferea
version    : 1.12.3
release    : 11
source     :
    - https://github.com/lwindolf/liferea/archive/v1.12.3.tar.gz : 9c7b0f7053c56da15ed1998dedf75b419a365e517d937fe74d31fa75eb8fa796
license    : GPL-2.0-only
component  : network.news
summary    : A desktop feed reader and news aggregator
description: |
    A desktop feed reader and news aggregator
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
rundeps    :
    - python3-cairo # tray icon plugin
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
