name       : liferea
version    : 1.12.1
release    : 7
source     :
    - https://github.com/lwindolf/liferea/releases/download/v1.12.1/liferea-1.12.1.tar.bz2 : b8ed5bc7eedb3858725a84cac5bf3c5ac13b0c536d2355096bde32d9451f1d93
license    : GPL-2.0
component  : network.news
summary    : A desktop feed reader and news aggregator
description: |
    A desktop feed reader and news aggregator
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
rundeps    :
    - python3-cairo # tray icon plugin
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
