name       : liferea
version    : 1.13.8
release    : 26
source     :
    - https://github.com/lwindolf/liferea/archive/refs/tags/v1.13.8.tar.gz : 3f57a8d568dd02048cc1fd788304a760085f66e4db889ccf5c25a2b6a6978c4b
license    : GPL-2.0-only
homepage   : https://lzone.de/liferea
component  : network.news
summary    : A desktop feed reader and news aggregator
description: |
    A desktop feed reader and news aggregator
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libxslt)
    - pkgconfig(webkit2gtk-4.0)
rundeps    :
    - python3-cairo # tray icon plugin
environment: |
    export WEBKIT_DISABLE_COMPOSITING_MODE=1 # temp workaround: https://github.com/lwindolf/liferea/issues/767
setup      : |
    %autogen --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
