name       : liferea
version    : 1.14.6
release    : 31
source     :
    - https://github.com/lwindolf/liferea/archive/refs/tags/v1.14.6.tar.gz : 6de1643ca91a23436cd6e8d461ffffac66c7ccdb59b201c62e1f973a1ef575cd
license    : GPL-2.0-or-later
homepage   : https://lzone.de/liferea
component  : network.news
summary    : A desktop feed reader and news aggregator
description: |
    Liferea is a desktop feed reader/news aggregator that brings together all of the content from your favorite subscriptions into a simple interface that makes it easy to organize and browse feeds. Its GUI is similar to a desktop mail/news client, with an embedded web browser.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libxslt)
    - pkgconfig(webkit2gtk-4.0)
    - gettext-devel
rundeps    :
    - python3-cairo # tray icon plugin
environment: |
    export WEBKIT_DISABLE_COMPOSITING_MODE=1 # temp workaround: https://github.com/lwindolf/liferea/issues/767
setup      : |
    %autogen --disable-static --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
